---
- name: reload systemd
  systemd:
    daemon_reload: true
  become: true

- name: enable signoz service
  systemd:
    name: signoz
    enabled: true
  become: true

- name: restart signoz
  shell: |
    cd {{ docker_compose_path }}
    sg docker -c "docker compose restart"
  become_user: "{{ deployment_user | default(signoz_deployment_user) }}"
  become: true
  ignore_errors: true

- name: restart docker
  systemd:
    name: docker
    state: restarted
  become: true