---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: enable signoz service
  systemd:
    name: signoz
    enabled: true

- name: restart signoz
  shell: |
    cd {{ docker_compose_path }}
    sg docker -c "docker compose restart"
  ignore_errors: true

- name: restart docker
  systemd:
    name: docker
    state: restarted
